# Linear Algebra

## Scalars, Vectors, Matrices and Tensors

Vamos começar com algumas definições básicas:

<img src="images/scalar-vector-matrix-tensor.png" width="400" alt="An example of a scalar, a vector, a matrix and a tensor" title="Difference between a scalar, a vector, a matrix and a tensor">
<em>Diferença entre um Scalar, Vetor, Matriz e um Tensor</em>

- __Um escalar é um único número (Ou elemento)__
- __Um vetor é uma matriz de números__.

$$
{x} =\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$$

- Uma Matriz é um 2-D Vetor

$$
{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

- Um `Tensor` é um __n-dimensional__ Vector com __n > 2__
  
 - __Scalar__ são escritos em __lowercase__ - "n"  
 - __Vector__ são escritos em __lowercase__ - "x"  
 - Matrizes são escritas em __uppercase__ - "X"

### Exemplo 1.
Crie um Vetor com __Python__ e __NumPy__. Vamos começar criando um Vetor, esse vai ser simplesmente um __1-dimensional__ Vetor.

In [1]:
# Importa a biblioteca NumPy
import numpy as np

In [3]:
# Cria um vetor com o método array() do NumPy - 1x4
# - 1 Dimensão (1-dimensional)
# - 4 Elementos
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

### Exemplo 2.
Crie uma matriz (3x2) com colchetes aninhados.  
O método array() pode ser utilizado para criar __2-dimensional__ vetor/matriz com colchetes aninhados:

In [4]:
# Cria uma matrix 3x2 com o método array() do NumPy:
# - 3 Dimensões
# - 2 Elementos cada
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

__NOTE:__  
  
> Veja que uma __Matrix__ é formada por um conjuntos de __Vetores__.  
  
```  
[ 
  []
  []
  []
]  
```

## Shape  
  
O __shape__ de uma matriz __(isto é, suas dimensões)__ informa o número de valores para cada dimensão. Para um array 2-dimensional, ele fornecerá o número de linhas e o número de colunas. Vamos encontrar o __shape__ do nosso Vetor 2-dimensional anterior __"A"__.

Como __"A"__ é um array Numpy (foi criado com a função array()), você pode acessar sua forma com:

In [5]:
A.shape

(3, 2)

Logo, temos uma Matriz __3x2__:
 - 3 Dimensões
 - 2 Elementos cada
 
Nós podemos ver que __"A"__ tem:  

 - 3 Linhas
 - 2 Colunas

Vamos verificar o __shape__ do nosso primeiro array/vetor:

In [6]:
x.shape

(4,)

Como experado, você pode ver que __"x"__ tem apenas uma(1) dimensão (1-dimensional). O número corresponde ao tamanho do array.

In [7]:
# Verifica o tamanho do array
len(x)

4

# Transposition - Transposição

Com a transposição, você pode converter um vetor de linha em um vetor de coluna e vice-versa:

<img src="images/vector-transposition.png" alt="Transposition of a vector" title="Vector transposition" width="200">
<em>Transposição Vetorial</em>

A transposição ${A}^{\text{T}}$ da matriz ${A}$ corresponde aos eixos espelhados. Se a matriz é uma matriz quadrada __(mesmo número de colunas e linhas)__:

<img src="images/square-matrix-transposition.png" alt="Transposition of a square matrix" title="Square matrix transposition" width="300">
<em>Transposição matricial quadrada</em>

Se a matriz não é quadrada, a ideia é a mesma:

<img src="images/non-squared-matrix-transposition.png" alt="Transposition of a square matrix" title="Non square matrix transposition" width="300">
<em>Transposição de matriz não quadrada</em>

O sobrescrito $^\text{T}$ é usado para matrizes transpostas.

$$
{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}
$$

$$
{A}^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2}
\end{bmatrix}
$$

O __shape__ ($m \times n$) é invertida e se torna ($n \times m$).

<img src="images/dimensions-transposition-matrix.png" alt="Dimensions of matrix transposition" title="Dimensions of matrix transposition" width="300">
<em>Dimensões da Transposição Matricial</em>

### Exemplo 3. 
Crie uma matriz __"A"__ e transponha-a

In [8]:
# Cria uma Matriz 3x2:
# - 3 Dimensões
# - 2 Elementos cada
A = np.array([[10, 20], [30, 40], [50, 60]])
A

array([[10, 20],
       [30, 40],
       [50, 60]])

In [9]:
# Verifica o shape da Matriz
A.shape

(3, 2)

In [10]:
# Transpõem a Matriz
A_T = A.T
A_T

array([[10, 30, 50],
       [20, 40, 60]])

__NOTE:__  
Podemos ver que o número de colunas torna-se o número de linhas com transposição e vice-versa.

Agora vamos verificar as dimensões da Matriz transposta:

In [11]:
# Verifica as dimensões
A_T.shape

(2, 3)

# Addition - Adição

<img src="images/matrix-addition.png" alt="Addition of two matrices" title="Addition of two matrices" width="300">
<em>Adição de duas Matrizes</em>

Matrizes podem ser adicionadas se tiverem as mesmas dimensões:

$${A} + {B} = {C}$$

Cada célula de  ${A}$ é adicionado à célula correspondente de ${B}$:

$${A}_{i,j} + {B}_{i,j} = {C}_{i,j}$$

 - $i$ é o índex da linha
 - E o $j$ o índex da coluna.

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix}
$$

A dimensão de ${A}$, ${B}$ e ${C}$ são idênticos. Vamos verificar isso em um exemplo:

### Exemplo 4 
Crie duas matrizes ${A}$ e ${B}$ e adicione-as.  
Com __Numpy__ você pode adicionar matrizes como adicionaria vetores ou escalares.

In [12]:
# Cria uma Matriz "A" - 3x2
# - 3 Dimensões
# - 2 Elementos cada
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# Verifica o shape(dimensão) da Matriz "A"
A.shape

(3, 2)

In [14]:
# Cria uma Matriz "B" - 3x2
# - 3 Dimensões
# - 2 Elementos cada
B = np.array([[1, 4], [2, 5], [2,3]])
B

array([[1, 4],
       [2, 5],
       [2, 3]])

In [15]:
# Verifica o shape(dimensão) da Matriz "B"
A.shape

(3, 2)

In [16]:
# Aplica a adição nas Matrizes "A" e "B" e salva na Matriz "C"
C = A + B
C

array([[2, 6],
       [5, 9],
       [7, 9]])

In [17]:
# Verifica o shape(dimensão) da Matriz "C"
C.shape

(3, 2)

Também é possível adicionar um escalar a uma matriz. Isso significa adicionar este escalar a cada célula da matriz.

$$
\alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix}
$$

#### Exemplo 5. 
Adicione um escalar a uma matriz. 

In [18]:
# Exibe a Matriz "A" novamente
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
# Adiciona um elemento 4 (como se fosse um scalar) na Matriz "A"
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Broadcasting - Transmissão 

Numpy pode manipular operações em matrizes de diferentes formas. A matriz menor será estendida para corresponder à forma da maior. A vantagem é que isso é feito celula por celula (como qualquer operação vetorizada em Numpy). Na verdade, usamos a transmissão(Broadcasting) no exemplo 5. O escalar foi convertido em uma matriz da mesma forma que ${A}$.

Aqui está outro exemplo genérico:

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix}
$$

É equivalente a

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$$


Onde o ($3 \times 1$) matriz é convertida para a forma correta ($3 \times 2$) copiando a primeira coluna. Numpy fará isso automaticamente se as formas puderem combinar.

#### Exemplo 6.   
Adicione duas matrizes de shapes(dimensões) diferentes:

In [20]:
# Cria uma Matriz "A" - 3x2
# - 3 Dimensões
# - 2 Elementos cada
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# Verifica o shape(dimensão) da Matriz "A"
A.shape

(3, 2)

In [22]:
# Cria uma Matriz "B" - 3x1
# - 3 Dimensões
# - 1 Elemento cada
B = np.array([[8], [9], [7]])
B

array([[8],
       [9],
       [7]])

In [23]:
# Verifica o shape(dimensão) da Matriz "B"
B.shape

(3, 1)

In [24]:
# Aplica o Broadcasting das Matrizes "A" e "B" e salva na Matriz "C"
C = A+B
C

array([[ 9, 10],
       [12, 13],
       [12, 13]])

In [25]:
# Verifica o shape(dimensão) da Matriz "C"
C.shape

(3, 2)

__References:__  
[Linear Algebra Series](https://hadrienj.github.io/deep-learning-book-series-home/)