# Introdução ao TensorFlow

 - __Tensor__ = Objeto matemático
 - __Flow__ = Fluxo  
 - __TensorFlow__ = Fluxo de um objeto matemático

O __Tensorflow - (Fluxo de um objeto matemático)__ é uma das bibliotecas mais amplamente utilizadas para implementar o aprendizado de máquina e outros algoritmos que envolvem grandes operações matemáticas. O Tensorflow foi desenvolvido pelo Google e é uma das bibliotecas de aprendizado de máquina mais populares no GitHub. O Google usa o Tensorflow para aprendizado de máquina em quase todos os aplicativos. Se você já usou o Google Photos ou o Google Voice Search, então já utilizou uma aplicação criada com a ajuda do TensorFlow. Vamos compreender os detalhes por trás do TensorFlow.

Matematicamente, um tensor é um vetor __N-dimensional__, significando que um tensor pode ser usado para representar conjuntos de dados __N-dimensionais__. Aqui está um exemplo:

![title](imagens/tensor1.png)

A figura acima mostra alguns tensores simplificados com dimensões mínimas. À medida que a dimensão continua crescendo, os dados se tornam mais e mais complexos. Por exemplo:

 - Se pegarmos um Tensor da forma (3x3), posso chamá-lo de matriz de 3 linhas e colunas
 - Se eu selecionar outro Tensor de forma (1000x3x3), posso chamá-lo como tensor ou conjunto de 1000 matrizes 3x3. Aqui chamamos (1000x3x3) como a forma ou dimensão do tensor resultante. Os tensores podem ser constantes ou variáveis.

![title](imagens/tensor2.png)

# Tensores - Examples

![title](imagens/tensor3.png)

# TensorFlow x NumPy

__TensorFlow__ e __NumPy__ são bastante semelhantes __(ambos são bibliotecas de matriz N-d)__. NumPy é o pacote fundamental para computação científica com Python. Ele contém um poderoso objeto array N-dimensional, funções sofisticadas (broadcasting) e etc. Acredito que os usuários Python não podem viver sem o NumPy. O NumPy tem suporte a matriz N-d, mas não oferece métodos para criar funções de tensor e automaticamente computar derivadas, além de não ter suporte a GPU, e esta é uma das principais razões para a existência do TensorFlow. Abaixo uma comparação entre NumPy e TensorFlow, e você vai perceber que muitas palavras-chave são semelhantes.

![title](imagens/tf_numpy.png)

# Grafo Computacional

Agora que sabemos o que um __tensor__ realmente significa é hora de entender o __fluxo__. Este fluxo refere-se a um __"Grafo Computacional"__ ou simplesmente um __"grafo"__. 
  
__Grafos Computacionais__ são uma boa maneira de pensar em expressões matemáticas. O conceito de grafo foi introduzido por __"Leonhard Euler"__ em 1736 para tentar resolver o problema das Pontes de Konigsberg. Grafos são modelos matemáticos para resolver problemas práticos do dia a dia, com várias aplicações no mundo real tais como:

 - Circuitos elétricos
 - Redes de distribuição
 - Relações de parentesco entre pessoas
 - Análise de redes sociais
 - Logística
 - Redes de estradas
 - Redes de computadores
 
Grafos são muito usados para modelar problemas em computação.  
  
Um Grafo é um __modelo matemático que representa relações entre objetos__. Um grafo G = (V, E) consiste de um conjunto de:

 - vértices __"V"__ (também chamados de nós)
 - ligados por um conjunto de bordas ou arestas __"E"__
 
#### Considere o diagrama abaixo:

![title](imagens/grafo1.png)

Existem três operações: duas adições e uma multiplicação. Ou seja: 

- c = a+b
- d = b+1
- e = c∗d

Para criar um grafo computacional, fazemos cada uma dessas operações nos nós, juntamente com as variáveis de entrada. Quando o valor de um nó é a entrada para outro nó, uma seta vai de um para outro e temos nesse caso um __"Grafo direcionado"__.

Esses tipos de grafos surgem o tempo todo em Ciência da Computação, especialmente ao falar sobre programas funcionais. Eles estão intimamente relacionados com as noções de grafos de dependência e grafos de chamadas. Eles também são a principal abstração por trás do popular framework de Deep Learning, o TensorFlow.

# NOTE:
Um grafo para execução de um modelo de Machine Learning pode ser bem grande e podemos executar sub-grafos (porções dos grafos) em dispositivos diferentes, como uma GPU. Exemplo:

![title](imagens/grafo2.png)

A figura acima explica a execução paralela de sub-grafos. Aqui estão 2 operações de multiplicação de matrizes, já que ambas estão no mesmo nível. Os nós são executados em __gpu_0__ e __gpu_1__ em paralelo.

# Modelo de Programação TensorFlow

> O principal objetivo de um programa TensorFlow é __"expressar uma computação numérica como um grafo direcionado"__.  
  
A figura abaixo é um exemplo de grafo de computação, que representa o cálculo de h = ReLU (Wx + b). Este é um componente muito clássico em muitas redes neurais, que conduz a transformação linear dos dados de entrada e, em seguida, alimenta uma linearidade (função de ativação linear retificada, neste caso).

![title](imagens/grafo3.png)

O grafo acima representa um cálculo de fluxo de dados; cada nó está em operação com zero ou mais entradas e zero ou mais saídas. As arestas do grafo são tensores que fluem entre os nós. Os clientes geralmente constroem um grafo computacional usando uma das linguagens frontend suportadas como Python e C ++ e, em seguida, iniciam o grafo em uma sessão a ser executada (Session é uma noção muito importante no TensorFlow, que estudaremos na sequência).

Vamos ver o grafo computacional acima em detalhes. Truncamos o grafo e deixamos a parte acima do nó ReLU, que é exatamente o cálculo h = ReLU (Wx + b).

![title](imagens/grafo4.png)

Podemos ver o grafo como um sistema, que tem entradas (os dados x), saída (h neste caso), variáveis com estado (W e b) e um monte de operações (matmul, add e ReLU). Deixe-me apresentar-lhe um por um.

- Placeholders: para alimentar a entrada para treinar o modelo ou fazer inferência, devemos ter uma porta de entrada para o grafo. Espaços reservados (Placeholders) são nós cujos valores são alimentados em tempo de execução. Normalmente, queremos alimentar entradas de dados, rótulos e hiper-parâmetros no modelo.


- Variáveis: quando treinamos um modelo, usamos variáveis para manter e atualizar parâmetros. Ao contrário de muitos tensores que fluem ao longo das margens do grafo, uma variável é um tipo especial de operação. Na maioria dos modelos de aprendizado de máquina, existem muitos parâmetros que temos que aprender, que são atualizados durante o treinamento. Variáveis são nós com estado que armazenam parâmetros e produzem seus valores atuais de tempos em tempos. Seus estados são mantidos em múltiplas execuções de um grafo. Por exemplo, os valores desses nós não serão atualizados até que uma etapa completa de treinamento usando um mini lote de dados seja concluída.


- Operações matemáticas: Neste grafo, existem três tipos de operações matemáticas. A operação MatMul multiplica dois valores de matriz; A operação Add adiciona elementos e a operação ReLU é ativada com a função linear retificada de elementos.

Variáveis devem ser explicitamente inicializadas. Quando criamos uma variável, passamos um tensor como seu valor inicial para o construtor variable (). O inicializador pode ser constantes, sequências e valores aleatórios. Neste caso, inicializamos o vetor de polarização b por constantes que são zeros e inicializamos a matriz de ponderações W por uniforme aleatório Observe que todos esses ops exigem que você especifique a forma dos tensores e que a forma se torne automaticamente a forma da variável , Neste caso, um tensor com forma (100,) e W é um tensor de classificação com forma (784, 100).

Para executar o cálculo, devemos lançar o grafo em um tf.Session. O que é uma sessão? Podemos entender uma sessão como um ambiente para executar o grafo. Na verdade, para fazer computação numérica eficiente em Python, normalmente usamos bibliotecas como o NumPy que realizam operações custosas computacionalmente, como a multiplicação de matrizes, usando código altamente eficiente implementado em outro idioma (C). Infelizmente, ainda há muita sobrecarga voltando para o Python em todas as operações. Essa sobrecarga é particularmente ruim se você quiser fazer cálculos em GPUs ou de maneira distribuída, onde pode haver um alto custo para transferir dados.

# Hello World

In [1]:
# Importa a biblioteca TensorFlow.
import tensorflow as tf

In [2]:
# Verifica a versão atual do T
tf.__version__

'1.1.0'

In [3]:
# Cria um tensor
# Esse tensor é adicionado como um nó ao grafo.
hello = tf.constant('Hello, TensorFlow!')

In [4]:
# Exibe o tensor criado.
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
# Inicia a sessão TensorFlow - Cria uma instância do objeto Session e salva na variável "sess".
sess = tf.Session()

In [6]:
# Exibe a sessão criada.
print(sess)

In [7]:
# - A partir da sessão(sess) chama o método run() e executa o nosso tensor "hello".
# Executa o Grafo Computacional
print(sess.run(hello))

b'Hello, TensorFlow!'


# Operações Matemáticas com Tensores

# Soma

In [8]:
# Constantes
# Cria dois "tensores" com o método "constant" do TensorFloe e passa como argumento os valores
# dos tensores, ou seja, 5 e 9.
const_a = tf.constant(5) # Tensor rank 0 ou escalar - [].
const_b = tf.constant(9) # Tensor rank 0 ou escalar - [].

In [9]:
# Exibe o Tensor "const_a".
print(const_a)

Tensor("Const_1:0", shape=(), dtype=int32)


In [10]:
# Soma os 2 tensores e salva na variável "total".
total = const_a + const_b

In [11]:
# Exibe a soma dos tensores.
print(total)

Tensor("add:0", shape=(), dtype=int32)


# NOTE:
Isso que nós fizemos até agora __não foi a soma dos tensores__. Lembram que nós trabalhamos com esses tensores como Grafos? Então, o que foi feito até agora foi:

 - __Definir os vertices(V) - Nodes__
 - __Definir às arestas(E)__

Agora o que precisamos é abrir uma Sessão TensorFlow para fazer a soma.

In [14]:
# Cria uma sessão TensorFlow, porém, agora essa sessão vai permanecer aberta.
# Depois printa a "sess.run(total)", ou seja, exibe o total(soma dos nodes).
with tf.Session() as sess:
    print('\nA soma do node1 com o node2 é: %f' % sess.run(total))


A soma do node1 com o node2 é: 14.000000


# NOTE:
Uma maneira bem mais simples de fazer essa operação é utilizando o método add() do TensorFlow. Veja abaixo:

In [17]:
# Cria dois tensores com os valores 5 e 9
node1 = tf.constant(5, dtype=tf.int32)
node2 = tf.constant(9, dtype=tf.int32)

# Cria um terceiro tensor "node3", porém, esse tensor vai receber a adição(add()) dos dois tensores.
node3 = tf.add(node1, node2)

# Cria a sessão TF
sess = tf.Session()
 
# Executa o grafo com o método run() da sessão, ou seja, abre a sessão.
print("\nA soma do node1 com o node2 é:", sess.run(node3))
 
# Fecha a sessão.
sess.close()


A soma do node1 com o node2 é: 14


# Subtração

Veja abaixo que é possível criar "tensores" com valores randômicos, esses valores randômicos porem ser:

 - Normal
 - Uniforme

In [19]:
# Tensores randômicos
rand_a = tf.random_normal([3], 2.0) # Tensor randômico normal.
rand_b = tf.random_uniform([3], 1.0, 4.0) # Tensor randômico uniforme.

In [20]:
# Exibe o tensor "rand_a".
print(rand_a)

Tensor("random_normal:0", shape=(3,), dtype=float32)


In [21]:
# Exibe o tensor "rand_b".
print(rand_b)

Tensor("random_uniform:0", shape=(3,), dtype=float32)


In [22]:
# Utiliza o método subtract() do TensorFlow e passa como argumento os tensores "rand_a" e "rand_b".
# O retorno do método fica no objeto "diff".
diff = tf.subtract(rand_a, rand_b)

In [23]:
# Agora vamos abrir a sessão e exibir:
# - O valor do tensor "rand_a"
# - O valor do tensor "rand_b"
# - Executa o grafo com o métood run() do objeto Session.
with tf.Session() as sess:
    print('\nTensor rand_a: ', sess.run(rand_a))
    print('\nTensor rand_b: ', sess.run(rand_b))
    print('\nSubtração entre os 2 tensores é: ', sess.run(diff))


Tensor rand_a:  [-0.06870723  2.1538513   3.0993347 ]

Tensor rand_b:  [3.2446578 2.5672998 3.6344986]

Subtração entre os 2 tensores é:  [-2.0652215 -0.7301471 -2.6839275]


# Divisão

In [24]:
# Cria dois tensores e passa como argumento os valores 21 e 7.
node1 = tf.constant(21, dtype=tf.int32)
node2 = tf.constant(7, dtype=tf.int32)

In [25]:
# Utiliza o método div() do TensorFlow para fazer a divisão entre Tensores.
div = tf.div(node1, node2)

In [27]:
# Cria uma Sessão(Session) e executa o grafo computaiconal.
with tf.Session() as sess:
    print('\nDivisão entre os 2 tensores é: ', sess.run(div)) # Utiliza o método run() do objeto Session.


Divisão entre os 2 tensores é:  3


# Multiplicação

#### NOTE:  
Para calcular __"A"__ vezes __"B"__, __A.B__, o número de colunas de __"A"__ tem que ser igual ao número de linhas __"B"__. Então, podemos calcular __A.B__ se:

 - __"A"__ é uma matriz - __n x m__
 - E __"B"__ é uma matriz - __m x p__ 


Uma multiplicação de matriz é a multiplicação de uma linha com os elementos de uma coluna, veja o exemplo abaixo:

![title](imagens/mult02.png)

In [28]:
# Criando tensores "tensor_a" e "tensor_b".
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.],[7.]])

In [29]:
# Exibe o tensor "tensor_a".
print(tensor_a)

Tensor("Const_9:0", shape=(1, 2), dtype=float32)


In [30]:
# Exibe o tensor "tensor_b".
print(tensor_b)

Tensor("Const_10:0", shape=(2, 1), dtype=float32)


In [31]:
# Multiplicação
# tf.multiply(X, Y) executa multiplicação element-wise 
# https://www.tensorflow.org/api_docs/python/tf/multiply
prod = tf.multiply(tensor_a, tensor_b)

In [32]:
# Executa a sessão
with tf.Session() as sess:
    print('\ntensor_a: \n', sess.run(tensor_a))
    print('\ntensor_b: \n', sess.run(tensor_b))
    print('\nProduto Element-wise Entre os Tensores: \n', sess.run(prod))


tensor_a: 
 [[4. 2.]]

tensor_b: 
 [[3.]
 [7.]]

Produto Element-wise Entre os Tensores: 
 [[12.  6.]
 [28. 14.]]


# NOTE:  
Lembre que operações com matrizes é sempre __LINHA POR COLUNA__:  

```  
[4 , 2] x [3]  = [12 , 12]  
          [7]    [28 , 14]  
```

![title](imagens/mult01.png)

In [33]:
# Outro exemplo de Multiplicação de Matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [34]:
print(mat_a)

Tensor("Const_11:0", shape=(3, 2), dtype=int32)


In [35]:
print(mat_b)

Tensor("Const_12:0", shape=(2, 3), dtype=int32)


In [36]:
# Multiplicação
# tf.matmul(X, Y) executa multiplicação entre matrizes 
# https://www.tensorflow.org/api_docs/python/tf/matmul
mat_prod = tf.matmul(mat_a, mat_b)

In [37]:
# Executa a sessão
with tf.Session() as sess:
    print('\nTensor mat_a: \n', sess.run(mat_a))
    print('\nTensor mat_b: \n', sess.run(mat_b))
    print('\nProduto Element-wise Entre os Tensores (Matrizes): \n', sess.run(mat_prod))


Tensor mat_a: 
 [[2 3]
 [9 2]
 [4 5]]

Tensor mat_b: 
 [[6 4 5]
 [3 7 2]]

Produto Element-wise Entre os Tensores (Matrizes): 
 [[21 29 16]
 [60 50 49]
 [39 51 30]]


![title](imagens/mult02.png)  
  
![title](imagens/matrizes.png)

# Usando Variáveis

O __TensorFlow__ também possui nodes variáveis que podem conter dados variáveis. Elas são usados principalmente para manter e atualizar parâmetros de um modelo de treinamento.

Variáveis são buffers na memória contendo tensores. Elas devem ser inicializados e podem ser salvas durante e após o treinamento. Você pode restaurar os valores salvos posteriormente para exercitar ou analisar o modelo.

Uma diferença importante a notar entre uma __constante__ e uma __variável__ é:

 - O valor de uma constante é armazenado no grafo e seu valor é replicado onde o grafo é carregado
 - Uma variável é armazenada separadamente e pode estar em um servidor de parâmetros.

In [38]:
# Importa a biblioteca TensorFlow.
import tensorflow as tf
 
# Criando um node no grafo computacional
node = tf.Variable(tf.zeros([2,2])) # Utiliza o método zeros() do TensorFLow para o vetor/matriz de zeros.
 
# Executando o grafo computacional
with tf.Session() as sess:
 
    # Inicializando as variábeis
    sess.run(tf.global_variables_initializer())
 
    # Avaliando o node
    print("\nTensor Original:\n", sess.run(node))
 
    # Adição element-wise no tensor
    node = node.assign(node + tf.ones([2,2]))
 
    # Avaliando o node novamente
    print("\nTensor depois da adição:\n", sess.run(node))


Tensor Original:
 [[0. 0.]
 [0. 0.]]

Tensor depois da adição:
 [[1. 1.]
 [1. 1.]]


# Usando Placeholders

O que fazer quando precisamos criar tensores, porém ainda não sabemos os valores do mesmos? __What?__ Bem suponha que em algum momento nós precisamos criar tensores, mas os seus tamanhos depende de outras saídas(outputs) como reserva memória para eles? Simples, utilize a função __placeholder()__ do TensorFlow.

Essa função recebe os seguintes argumentos:
- __O tipo de dado (int32)__
- __O shape do tensor(vetor, matriz), ou seja, as dimensões__

In [39]:
# Importa a biblioteca TensorFlow.
import tensorflow as tf
 
# Utiliza a função placeholder() do TensorFlow para reserva espaço na memória
a = tf.placeholder(tf.int32, shape=(3,1))
b = tf.placeholder(tf.int32, shape=(1,3))

# Multiplica os tensores "a" e "b" e salva no objeto "c".
c = tf.matmul(a,b)
 
# - Abre uma Sessão(Session) TensorFlow
# - Utiliza o método run() do TensorFLow para executar o Grafo Computacional
# - Utiliza o argumento "feed_dict" que é um tipo de dicinário que relaciona os tensores "a" e "b"
#   com os valores que vamos passar para eles.
with tf.Session() as sess:
    print(sess.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]}))

[[3 6 9]
 [2 4 6]
 [1 2 3]]


![title](imagens/mult02.png)